---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

Here, we're just setting a few options.

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

```

Now, we're preparing our data for the codebook.

```{r prepare_codebook}
library(codebook)
codebook_data <- rio::import("https://osf.io/s87kd/download", "csv")
# to import an SPSS file from the same folder uncomment and edit the line below
# codebook_data <- rio::import("mydata.sav")
# for Stata
# codebook_data <- rio::import("mydata.dta")
# for CSV
# codebook_data <- rio::import("mydata.csv")

# omit the following lines, if your missing values are already properly labelled
codebook_data <- detect_missing(codebook_data,
    only_labelled = TRUE, # only labelled values are autodetected as
                                   # missing
    negative_values_are_missing = FALSE, # negative values are missing values
    ninety_nine_problems = TRUE,   # 99/999 are missing values, if they
                                   # are more than 5 MAD from the median
    )

# If you are not using formr, the codebook package needs to guess which items
# form a scale. The following line finds item aggregates with names like this:
# scale = scale_1 + scale_2R + scale_3R
# identifying these aggregates allows the codebook function to
# automatically compute reliabilities.
# However, it will not reverse items automatically.
codebook_data <- detect_scales(codebook_data)

library(labelled)
library(dplyr)
dict <- rio::import("https://osf.io/cs678/download", "csv")

var_label(codebook_data)  <-  dict　 %>% 
  select(variable,  label) %>% 
  dict_to_list()

val_labels(codebook_data$gender) <- c("male"=  1,  "female"=  2)
val_labels(codebook_data$education)  <-  c("in  high  school"=  1,"finished  high  school"=  2,"some  college"=  3,"college  graduate"=  4,"graduate  degree"=  5)

add_likert_labels  <-  function(x){
  val_labels(x)  <-  c("Very  Inaccurate"=  1,
                       "Moderately  Inaccurate"=  2,
                       "Slightly  Inaccurate"=  3,
                       "Slightly  Accurate"=  4,
                       "Moderately  Accurate"=  5,
                       "Very  Accurate"=  6) 
  x
}

likert_items  <-  dict %>% 
  filter(Big6 !="") %>% 
  pull(variable)

codebook_data  <-  codebook_data %>% 
  mutate_at(likert_items,  add_likert_labels)


reversed_items  <-  dict %>% 
  filter  (Keying  ==  -1) %>% 
  pull(variable)

codebook_data  <-  codebook_data　 %>% 
  rename_at(reversed_items,  add_R)

codebook_data  <-  codebook_data　 %>% 
  mutate_at(vars(matches("\\dR$")),reverse_labelled_values)

codebook_data$extraversion  <-  codebook_data　 %>% 
  select(E1R:E5) %>% 
  aggregate_and_document_scale()


metadata(codebook_data)$name  <-  "25 Personality items representing 5 factors"
metadata(codebook_data)$description  <-  "25  personality  self  report  items    taken  from  the  International    Personality  Item  Pool  (ipip.ori.org)"
metadata(codebook_data)$creator  <-  "William  Revelle"
metadata(codebook_data)$citation  <-  "Revelle,  W.,  Wilt,  J.,  &  Rosenthal,  A.    (2010).  Individual  differences  in    cognition:  New  methods  for  examining    the  personality-cognition  link.  In  A.    Gruszka,  G.  Matthews,  &  B.  Szymura    (Eds.),  Handbook  of  individual    differences  in  cognition:  Attention,    memory,  and  executive  control  (pp.    27–49).  New  York,  NY:  Springer."
metadata(codebook_data)$url  <-  "https://CRAN.R-project.org/package=psych"
metadata(codebook_data)$datePublished  <-  "2010-01-01"
metadata(codebook_data)$  temporalCoverage  <-  "Spring 2010"
metadata(codebook_data)$  spatialCoverage  <-  "Online"

rio::export(codebook_data, "bfi.rds")
```


Create codebook

```{r codebook}
codebook(codebook_data)
```
